databases:
  database1:
    type: mysql
    host: db1.example.invalid
    port: 3306
    database: sample_process_db_1
    table: sample_measurements

  database2:
    type: mysql
    host: db2.example.invalid
    port: 3306
    database: sample_process_db_2
    table: sample_measurements

  database3:
    type: mssql
    host: db3.example.invalid
    port: 1433
    database: sample_process_db_3
    table: sample_main_data

  database4:
    type: mysql
    host: db4.example.invalid
    port: 3306
    database: sample_process_db_4
    table: sample_measurements
